"""add placeholder to form fields

Revision ID: c725450c5b74
Revises: 87938488130b
Create Date: 2025-11-11 14:48:53.747167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c725450c5b74'
down_revision: Union[str, None] = '87938488130b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_fields', sa.Column('placeholder', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_fields', 'placeholder')
    # ### end Alembic commands ###
